sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-nfs-server-image .
script:
  # the "yast-travis-ruby" script is included in the base yastdevel/ruby image
  # see https://github.com/yast/docker-yast-ruby/blob/master/yast-travis-ruby
  # exclude the yardoc step, we run the more strict check:doc late
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-nfs-server-image yast-travis-ruby -x yardoc
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-nfs-server-image rake check:doc
